[package]
name = "rfs_damage"
version = "0.1.0"
edition = "2021"

[dependencies]
rfs_core = { path = "../core" }
serde = { workspace = true, features = ["derive"] }
smallvec = { workspace = true }
parking_lot = { workspace = true }
fastrand = { workspace = true }
petgraph = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }